CREATE TABLE direction_age_categories
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    age_category SMALLINT                                NOT NULL,
    direction_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_direction_age_categories PRIMARY KEY (id)
);

ALTER TABLE direction_age_categories
    ADD CONSTRAINT FK_DIRECTION_AGE_CATEGORIES_ON_DIRECTION FOREIGN KEY (direction_id) REFERENCES directions (id);