CREATE TABLE child_to_direction
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    child_id                  BIGINT                                  NOT NULL,
    status                    SMALLINT                                NOT NULL,
    queue_status              SMALLINT                                NOT NULL,
    direction_id              BIGINT,
    direction_age_category_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_child_to_direction PRIMARY KEY (id)
);

ALTER TABLE child_to_direction
    ADD CONSTRAINT FK_CHILD_TO_DIRECTION_ON_DIRECTION FOREIGN KEY (direction_id) REFERENCES directions (id);

ALTER TABLE child_to_direction
    ADD CONSTRAINT FK_CHILD_TO_DIRECTION_ON_DIRECTION_AGE_CATEGORY FOREIGN KEY (direction_age_category_id) REFERENCES direction_age_categories (id);