CREATE TABLE platforms
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name  VARCHAR(255)                            NOT NULL,
    short_name VARCHAR(255)                            NOT NULL,
    address    VARCHAR(255)                            NOT NULL,
    verified   BOOLEAN                                 NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_platforms PRIMARY KEY (id)
);