CREATE TABLE events
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                      VARCHAR(255)                            NOT NULL,
    short_description         VARCHAR(255)                            NOT NULL,
    event_type                SMALLINT                                NOT NULL,
    event_format              SMALLINT                                NOT NULL,
    start_date_time           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_date_time             TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    event_venue               TEXT,
    description               TEXT,
    direction_id              BIGINT                                  NOT NULL,
    direction_age_category_id BIGINT                                  NOT NULL,
    version                   INTEGER,
    CONSTRAINT pk_events PRIMARY KEY (id)
);

ALTER TABLE events
    ADD CONSTRAINT FK_EVENTS_ON_DIRECTION FOREIGN KEY (direction_id) REFERENCES directions (id);

ALTER TABLE events
    ADD CONSTRAINT FK_EVENTS_ON_DIRECTION_AGE_CATEGORY FOREIGN KEY (direction_age_category_id) REFERENCES direction_age_categories (id);