CREATE TABLE directions
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    description  VARCHAR(255)                            NOT NULL,
    age_category SMALLINT                                NOT NULL,
    icon_id      BIGINT,
    user_id      BIGINT,
    CONSTRAINT pk_directions PRIMARY KEY (id)
);